// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: iotest_mfa.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// Minimal standalone proto for the session 1.10 spike.
/// Defines ONLY the messages needed for the 3 gRPC calls:
///   CreateAuthenticateChallenge, CreateRegisterChallenge, AddMFADeviceSync.
/// Field NUMBERS match Teleport v18.9.1 exactly (that's what matters on the
/// wire for gRPC). Field *names* use snake_case (proto3 convention) so
/// SwiftProtobuf generates clean camelCase Swift property names. The JSON
/// tags differ from Teleport's, but that only matters for the HTTP/JSON API
/// which we are NOT using — gRPC uses the binary protobuf wire format, keyed
/// by field number.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ── MFA v1 ChallengeExtensions (from mfa/v1/mfa.proto) ──
enum Proto_ChallengeScope: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case login // = 1
  case passwordlessLogin // = 2
  case headlessLogin // = 3
  case manageDevices // = 4
  case accountRecovery // = 5
  case userSession // = 6
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .login
    case 2: self = .passwordlessLogin
    case 3: self = .headlessLogin
    case 4: self = .manageDevices
    case 5: self = .accountRecovery
    case 6: self = .userSession
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .login: return 1
    case .passwordlessLogin: return 2
    case .headlessLogin: return 3
    case .manageDevices: return 4
    case .accountRecovery: return 5
    case .userSession: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Proto_ChallengeScope] = [
    .unspecified,
    .login,
    .passwordlessLogin,
    .headlessLogin,
    .manageDevices,
    .accountRecovery,
    .userSession,
  ]

}

enum Proto_DeviceUsage: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case mfa // = 1
  case passwordless // = 2
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .mfa
    case 2: self = .passwordless
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .mfa: return 1
    case .passwordless: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Proto_DeviceUsage] = [
    .unspecified,
    .mfa,
    .passwordless,
  ]

}

enum Proto_DeviceType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0
  case totp // = 1
  case webauthn // = 2
  case sso // = 3
  case browser // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .totp
    case 2: self = .webauthn
    case 3: self = .sso
    case 4: self = .browser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .totp: return 1
    case .webauthn: return 2
    case .sso: return 3
    case .browser: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Proto_DeviceType] = [
    .unspecified,
    .totp,
    .webauthn,
    .sso,
    .browser,
  ]

}

struct Proto_ContextUser: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_Passwordless: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_ChallengeExtensions: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var scope: Proto_ChallengeScope = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ── WebAuthn types (from legacy/types/webauthn/webauthn.proto) ──
/// Field numbers match; names snake_cased for clean Swift.
struct Proto_CredentialAssertion: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var publicKey: Proto_PublicKeyCredentialRequestOptions {
    get {return _publicKey ?? Proto_PublicKeyCredentialRequestOptions()}
    set {_publicKey = newValue}
  }
  /// Returns true if `publicKey` has been explicitly set.
  var hasPublicKey: Bool {return self._publicKey != nil}
  /// Clears the value of `publicKey`. Subsequent reads from it will return its default value.
  mutating func clearPublicKey() {self._publicKey = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _publicKey: Proto_PublicKeyCredentialRequestOptions? = nil
}

struct Proto_PublicKeyCredentialRequestOptions: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var challenge: Data = Data()

  var timeoutMs: Int64 = 0

  var rpID: String = String()

  var allowCredentials: [Proto_CredentialDescriptor] = []

  var userVerification: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_CredentialDescriptor: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var type: String = String()

  var id: Data = Data()

  var transports: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_CredentialAssertionResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var type: String = String()

  var rawID: Data = Data()

  var response: Proto_AuthenticatorAssertionResponse {
    get {return _response ?? Proto_AuthenticatorAssertionResponse()}
    set {_response = newValue}
  }
  /// Returns true if `response` has been explicitly set.
  var hasResponse: Bool {return self._response != nil}
  /// Clears the value of `response`. Subsequent reads from it will return its default value.
  mutating func clearResponse() {self._response = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _response: Proto_AuthenticatorAssertionResponse? = nil
}

struct Proto_AuthenticatorAssertionResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var clientDataJson: Data = Data()

  var authenticatorData: Data = Data()

  var signature: Data = Data()

  var userHandle: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_CredentialCreation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var publicKey: Proto_PublicKeyCredentialCreationOptions {
    get {return _publicKey ?? Proto_PublicKeyCredentialCreationOptions()}
    set {_publicKey = newValue}
  }
  /// Returns true if `publicKey` has been explicitly set.
  var hasPublicKey: Bool {return self._publicKey != nil}
  /// Clears the value of `publicKey`. Subsequent reads from it will return its default value.
  mutating func clearPublicKey() {self._publicKey = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _publicKey: Proto_PublicKeyCredentialCreationOptions? = nil
}

struct Proto_PublicKeyCredentialCreationOptions: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var challenge: Data = Data()

  var rp: Proto_RelyingPartyEntity {
    get {return _rp ?? Proto_RelyingPartyEntity()}
    set {_rp = newValue}
  }
  /// Returns true if `rp` has been explicitly set.
  var hasRp: Bool {return self._rp != nil}
  /// Clears the value of `rp`. Subsequent reads from it will return its default value.
  mutating func clearRp() {self._rp = nil}

  var user: Proto_UserEntity {
    get {return _user ?? Proto_UserEntity()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var timeoutMs: Int64 = 0

  var attestation: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _rp: Proto_RelyingPartyEntity? = nil
  fileprivate var _user: Proto_UserEntity? = nil
}

struct Proto_RelyingPartyEntity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_UserEntity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var name: String = String()

  var displayName: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_CredentialCreationResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var type: String = String()

  var rawID: Data = Data()

  var response: Proto_AuthenticatorAttestationResponse {
    get {return _response ?? Proto_AuthenticatorAttestationResponse()}
    set {_response = newValue}
  }
  /// Returns true if `response` has been explicitly set.
  var hasResponse: Bool {return self._response != nil}
  /// Clears the value of `response`. Subsequent reads from it will return its default value.
  mutating func clearResponse() {self._response = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _response: Proto_AuthenticatorAttestationResponse? = nil
}

struct Proto_AuthenticatorAttestationResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var clientDataJson: Data = Data()

  var attestationObject: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// ── Auth service MFA messages (from authservice.proto) ──
struct Proto_MFAAuthenticateChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var totp: Proto_TOTPChallenge {
    get {return _totp ?? Proto_TOTPChallenge()}
    set {_totp = newValue}
  }
  /// Returns true if `totp` has been explicitly set.
  var hasTotp: Bool {return self._totp != nil}
  /// Clears the value of `totp`. Subsequent reads from it will return its default value.
  mutating func clearTotp() {self._totp = nil}

  var webauthnChallenge: Proto_CredentialAssertion {
    get {return _webauthnChallenge ?? Proto_CredentialAssertion()}
    set {_webauthnChallenge = newValue}
  }
  /// Returns true if `webauthnChallenge` has been explicitly set.
  var hasWebauthnChallenge: Bool {return self._webauthnChallenge != nil}
  /// Clears the value of `webauthnChallenge`. Subsequent reads from it will return its default value.
  mutating func clearWebauthnChallenge() {self._webauthnChallenge = nil}

  var mfaRequired: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _totp: Proto_TOTPChallenge? = nil
  fileprivate var _webauthnChallenge: Proto_CredentialAssertion? = nil
}

struct Proto_TOTPChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_MFAAuthenticateResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: Proto_MFAAuthenticateResponse.OneOf_Response? = nil

  var totp: Proto_TOTPResponse {
    get {
      if case .totp(let v)? = response {return v}
      return Proto_TOTPResponse()
    }
    set {response = .totp(newValue)}
  }

  var webauthn: Proto_CredentialAssertionResponse {
    get {
      if case .webauthn(let v)? = response {return v}
      return Proto_CredentialAssertionResponse()
    }
    set {response = .webauthn(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case totp(Proto_TOTPResponse)
    case webauthn(Proto_CredentialAssertionResponse)

  }

  init() {}
}

struct Proto_TOTPResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var code: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Proto_CreateAuthenticateChallengeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var request: Proto_CreateAuthenticateChallengeRequest.OneOf_Request? = nil

  var contextUser: Proto_ContextUser {
    get {
      if case .contextUser(let v)? = request {return v}
      return Proto_ContextUser()
    }
    set {request = .contextUser(newValue)}
  }

  var passwordless: Proto_Passwordless {
    get {
      if case .passwordless(let v)? = request {return v}
      return Proto_Passwordless()
    }
    set {request = .passwordless(newValue)}
  }

  var challengeExtensions: Proto_ChallengeExtensions {
    get {return _challengeExtensions ?? Proto_ChallengeExtensions()}
    set {_challengeExtensions = newValue}
  }
  /// Returns true if `challengeExtensions` has been explicitly set.
  var hasChallengeExtensions: Bool {return self._challengeExtensions != nil}
  /// Clears the value of `challengeExtensions`. Subsequent reads from it will return its default value.
  mutating func clearChallengeExtensions() {self._challengeExtensions = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Request: Equatable, Sendable {
    case contextUser(Proto_ContextUser)
    case passwordless(Proto_Passwordless)

  }

  init() {}

  fileprivate var _challengeExtensions: Proto_ChallengeExtensions? = nil
}

struct Proto_CreateRegisterChallengeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tokenID: String = String()

  var existingMfaResponse: Proto_MFAAuthenticateResponse {
    get {return _existingMfaResponse ?? Proto_MFAAuthenticateResponse()}
    set {_existingMfaResponse = newValue}
  }
  /// Returns true if `existingMfaResponse` has been explicitly set.
  var hasExistingMfaResponse: Bool {return self._existingMfaResponse != nil}
  /// Clears the value of `existingMfaResponse`. Subsequent reads from it will return its default value.
  mutating func clearExistingMfaResponse() {self._existingMfaResponse = nil}

  var deviceType: Proto_DeviceType = .unspecified

  var deviceUsage: Proto_DeviceUsage = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _existingMfaResponse: Proto_MFAAuthenticateResponse? = nil
}

struct Proto_MFARegisterChallenge: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var request: Proto_MFARegisterChallenge.OneOf_Request? = nil

  var webauthn: Proto_CredentialCreation {
    get {
      if case .webauthn(let v)? = request {return v}
      return Proto_CredentialCreation()
    }
    set {request = .webauthn(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Request: Equatable, Sendable {
    case webauthn(Proto_CredentialCreation)

  }

  init() {}
}

struct Proto_MFARegisterResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: Proto_MFARegisterResponse.OneOf_Response? = nil

  var webauthn: Proto_CredentialCreationResponse {
    get {
      if case .webauthn(let v)? = response {return v}
      return Proto_CredentialCreationResponse()
    }
    set {response = .webauthn(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable, Sendable {
    case webauthn(Proto_CredentialCreationResponse)

  }

  init() {}
}

struct Proto_AddMFADeviceSyncRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tokenID: String = String()

  var contextUser: Proto_ContextUser {
    get {return _contextUser ?? Proto_ContextUser()}
    set {_contextUser = newValue}
  }
  /// Returns true if `contextUser` has been explicitly set.
  var hasContextUser: Bool {return self._contextUser != nil}
  /// Clears the value of `contextUser`. Subsequent reads from it will return its default value.
  mutating func clearContextUser() {self._contextUser = nil}

  var newDeviceName: String = String()

  var newMfaResponse: Proto_MFARegisterResponse {
    get {return _newMfaResponse ?? Proto_MFARegisterResponse()}
    set {_newMfaResponse = newValue}
  }
  /// Returns true if `newMfaResponse` has been explicitly set.
  var hasNewMfaResponse: Bool {return self._newMfaResponse != nil}
  /// Clears the value of `newMfaResponse`. Subsequent reads from it will return its default value.
  mutating func clearNewMfaResponse() {self._newMfaResponse = nil}

  var deviceUsage: Proto_DeviceUsage = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _contextUser: Proto_ContextUser? = nil
  fileprivate var _newMfaResponse: Proto_MFARegisterResponse? = nil
}

struct Proto_AddMFADeviceSyncResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// We don't need the full MFADevice; just succeed.
  var device: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "proto"

extension Proto_ChallengeScope: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CHALLENGE_SCOPE_UNSPECIFIED"),
    1: .same(proto: "CHALLENGE_SCOPE_LOGIN"),
    2: .same(proto: "CHALLENGE_SCOPE_PASSWORDLESS_LOGIN"),
    3: .same(proto: "CHALLENGE_SCOPE_HEADLESS_LOGIN"),
    4: .same(proto: "CHALLENGE_SCOPE_MANAGE_DEVICES"),
    5: .same(proto: "CHALLENGE_SCOPE_ACCOUNT_RECOVERY"),
    6: .same(proto: "CHALLENGE_SCOPE_USER_SESSION"),
  ]
}

extension Proto_DeviceUsage: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DEVICE_USAGE_UNSPECIFIED"),
    1: .same(proto: "DEVICE_USAGE_MFA"),
    2: .same(proto: "DEVICE_USAGE_PASSWORDLESS"),
  ]
}

extension Proto_DeviceType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "DEVICE_TYPE_UNSPECIFIED"),
    1: .same(proto: "DEVICE_TYPE_TOTP"),
    2: .same(proto: "DEVICE_TYPE_WEBAUTHN"),
    3: .same(proto: "DEVICE_TYPE_SSO"),
    4: .same(proto: "DEVICE_TYPE_BROWSER"),
  ]
}

extension Proto_ContextUser: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ContextUser"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_ContextUser, rhs: Proto_ContextUser) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_Passwordless: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Passwordless"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_Passwordless, rhs: Proto_Passwordless) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_ChallengeExtensions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChallengeExtensions"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "scope"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.scope) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.scope != .unspecified {
      try visitor.visitSingularEnumField(value: self.scope, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_ChallengeExtensions, rhs: Proto_ChallengeExtensions) -> Bool {
    if lhs.scope != rhs.scope {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CredentialAssertion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CredentialAssertion"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "public_key"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._publicKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._publicKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CredentialAssertion, rhs: Proto_CredentialAssertion) -> Bool {
    if lhs._publicKey != rhs._publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_PublicKeyCredentialRequestOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PublicKeyCredentialRequestOptions"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "challenge"),
    2: .standard(proto: "timeout_ms"),
    3: .standard(proto: "rp_id"),
    4: .standard(proto: "allow_credentials"),
    6: .standard(proto: "user_verification"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.timeoutMs) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.rpID) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.allowCredentials) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.userVerification) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 1)
    }
    if self.timeoutMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timeoutMs, fieldNumber: 2)
    }
    if !self.rpID.isEmpty {
      try visitor.visitSingularStringField(value: self.rpID, fieldNumber: 3)
    }
    if !self.allowCredentials.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.allowCredentials, fieldNumber: 4)
    }
    if !self.userVerification.isEmpty {
      try visitor.visitSingularStringField(value: self.userVerification, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_PublicKeyCredentialRequestOptions, rhs: Proto_PublicKeyCredentialRequestOptions) -> Bool {
    if lhs.challenge != rhs.challenge {return false}
    if lhs.timeoutMs != rhs.timeoutMs {return false}
    if lhs.rpID != rhs.rpID {return false}
    if lhs.allowCredentials != rhs.allowCredentials {return false}
    if lhs.userVerification != rhs.userVerification {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CredentialDescriptor: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CredentialDescriptor"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "type"),
    2: .same(proto: "id"),
    3: .same(proto: "transports"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.id) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.transports) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularBytesField(value: self.id, fieldNumber: 2)
    }
    if !self.transports.isEmpty {
      try visitor.visitRepeatedStringField(value: self.transports, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CredentialDescriptor, rhs: Proto_CredentialDescriptor) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.id != rhs.id {return false}
    if lhs.transports != rhs.transports {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CredentialAssertionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CredentialAssertionResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    5: .same(proto: "id"),
    1: .same(proto: "type"),
    2: .standard(proto: "raw_id"),
    3: .same(proto: "response"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.rawID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._response) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.rawID.isEmpty {
      try visitor.visitSingularBytesField(value: self.rawID, fieldNumber: 2)
    }
    try { if let v = self._response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CredentialAssertionResponse, rhs: Proto_CredentialAssertionResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.type != rhs.type {return false}
    if lhs.rawID != rhs.rawID {return false}
    if lhs._response != rhs._response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_AuthenticatorAssertionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthenticatorAssertionResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "client_data_json"),
    2: .standard(proto: "authenticator_data"),
    3: .same(proto: "signature"),
    4: .standard(proto: "user_handle"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.clientDataJson) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.authenticatorData) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.userHandle) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientDataJson.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientDataJson, fieldNumber: 1)
    }
    if !self.authenticatorData.isEmpty {
      try visitor.visitSingularBytesField(value: self.authenticatorData, fieldNumber: 2)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 3)
    }
    if !self.userHandle.isEmpty {
      try visitor.visitSingularBytesField(value: self.userHandle, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_AuthenticatorAssertionResponse, rhs: Proto_AuthenticatorAssertionResponse) -> Bool {
    if lhs.clientDataJson != rhs.clientDataJson {return false}
    if lhs.authenticatorData != rhs.authenticatorData {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.userHandle != rhs.userHandle {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CredentialCreation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CredentialCreation"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "public_key"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._publicKey) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._publicKey {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CredentialCreation, rhs: Proto_CredentialCreation) -> Bool {
    if lhs._publicKey != rhs._publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_PublicKeyCredentialCreationOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PublicKeyCredentialCreationOptions"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "challenge"),
    2: .same(proto: "rp"),
    3: .same(proto: "user"),
    5: .standard(proto: "timeout_ms"),
    7: .same(proto: "attestation"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.challenge) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._rp) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.timeoutMs) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.attestation) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.challenge.isEmpty {
      try visitor.visitSingularBytesField(value: self.challenge, fieldNumber: 1)
    }
    try { if let v = self._rp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.timeoutMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timeoutMs, fieldNumber: 5)
    }
    if !self.attestation.isEmpty {
      try visitor.visitSingularStringField(value: self.attestation, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_PublicKeyCredentialCreationOptions, rhs: Proto_PublicKeyCredentialCreationOptions) -> Bool {
    if lhs.challenge != rhs.challenge {return false}
    if lhs._rp != rhs._rp {return false}
    if lhs._user != rhs._user {return false}
    if lhs.timeoutMs != rhs.timeoutMs {return false}
    if lhs.attestation != rhs.attestation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_RelyingPartyEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RelyingPartyEntity"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_RelyingPartyEntity, rhs: Proto_RelyingPartyEntity) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_UserEntity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserEntity"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .standard(proto: "display_name"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_UserEntity, rhs: Proto_UserEntity) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CredentialCreationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CredentialCreationResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    5: .same(proto: "id"),
    1: .same(proto: "type"),
    2: .standard(proto: "raw_id"),
    3: .same(proto: "response"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.rawID) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._response) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if !self.rawID.isEmpty {
      try visitor.visitSingularBytesField(value: self.rawID, fieldNumber: 2)
    }
    try { if let v = self._response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CredentialCreationResponse, rhs: Proto_CredentialCreationResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.type != rhs.type {return false}
    if lhs.rawID != rhs.rawID {return false}
    if lhs._response != rhs._response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_AuthenticatorAttestationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AuthenticatorAttestationResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "client_data_json"),
    2: .standard(proto: "attestation_object"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.clientDataJson) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.attestationObject) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.clientDataJson.isEmpty {
      try visitor.visitSingularBytesField(value: self.clientDataJson, fieldNumber: 1)
    }
    if !self.attestationObject.isEmpty {
      try visitor.visitSingularBytesField(value: self.attestationObject, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_AuthenticatorAttestationResponse, rhs: Proto_AuthenticatorAttestationResponse) -> Bool {
    if lhs.clientDataJson != rhs.clientDataJson {return false}
    if lhs.attestationObject != rhs.attestationObject {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_MFAAuthenticateChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MFAAuthenticateChallenge"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "totp"),
    3: .standard(proto: "webauthn_challenge"),
    4: .standard(proto: "mfa_required"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularMessageField(value: &self._totp) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._webauthnChallenge) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.mfaRequired) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._totp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._webauthnChallenge {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.mfaRequired != 0 {
      try visitor.visitSingularInt32Field(value: self.mfaRequired, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_MFAAuthenticateChallenge, rhs: Proto_MFAAuthenticateChallenge) -> Bool {
    if lhs._totp != rhs._totp {return false}
    if lhs._webauthnChallenge != rhs._webauthnChallenge {return false}
    if lhs.mfaRequired != rhs.mfaRequired {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_TOTPChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TOTPChallenge"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_TOTPChallenge, rhs: Proto_TOTPChallenge) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_MFAAuthenticateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MFAAuthenticateResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    2: .same(proto: "totp"),
    3: .same(proto: "webauthn"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: Proto_TOTPResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .totp(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .totp(v)
        }
      }()
      case 3: try {
        var v: Proto_CredentialAssertionResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .webauthn(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .webauthn(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .totp?: try {
      guard case .totp(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .webauthn?: try {
      guard case .webauthn(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_MFAAuthenticateResponse, rhs: Proto_MFAAuthenticateResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_TOTPResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TOTPResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_TOTPResponse, rhs: Proto_TOTPResponse) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CreateAuthenticateChallengeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateAuthenticateChallengeRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .standard(proto: "context_user"),
    4: .same(proto: "passwordless"),
    6: .standard(proto: "challenge_extensions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try {
        var v: Proto_ContextUser?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .contextUser(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .contextUser(v)
        }
      }()
      case 4: try {
        var v: Proto_Passwordless?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .passwordless(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .passwordless(v)
        }
      }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._challengeExtensions) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.request {
    case .contextUser?: try {
      guard case .contextUser(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .passwordless?: try {
      guard case .passwordless(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try { if let v = self._challengeExtensions {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CreateAuthenticateChallengeRequest, rhs: Proto_CreateAuthenticateChallengeRequest) -> Bool {
    if lhs.request != rhs.request {return false}
    if lhs._challengeExtensions != rhs._challengeExtensions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_CreateRegisterChallengeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateRegisterChallengeRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "token_id"),
    4: .standard(proto: "existing_mfa_response"),
    2: .standard(proto: "device_type"),
    3: .standard(proto: "device_usage"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tokenID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.deviceType) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.deviceUsage) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._existingMfaResponse) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tokenID.isEmpty {
      try visitor.visitSingularStringField(value: self.tokenID, fieldNumber: 1)
    }
    if self.deviceType != .unspecified {
      try visitor.visitSingularEnumField(value: self.deviceType, fieldNumber: 2)
    }
    if self.deviceUsage != .unspecified {
      try visitor.visitSingularEnumField(value: self.deviceUsage, fieldNumber: 3)
    }
    try { if let v = self._existingMfaResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_CreateRegisterChallengeRequest, rhs: Proto_CreateRegisterChallengeRequest) -> Bool {
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs._existingMfaResponse != rhs._existingMfaResponse {return false}
    if lhs.deviceType != rhs.deviceType {return false}
    if lhs.deviceUsage != rhs.deviceUsage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_MFARegisterChallenge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MFARegisterChallenge"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .same(proto: "webauthn"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try {
        var v: Proto_CredentialCreation?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .webauthn(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .webauthn(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .webauthn(let v)? = self.request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_MFARegisterChallenge, rhs: Proto_MFARegisterChallenge) -> Bool {
    if lhs.request != rhs.request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_MFARegisterResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MFARegisterResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    3: .same(proto: "webauthn"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try {
        var v: Proto_CredentialCreationResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .webauthn(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .webauthn(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .webauthn(let v)? = self.response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_MFARegisterResponse, rhs: Proto_MFARegisterResponse) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_AddMFADeviceSyncRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddMFADeviceSyncRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "token_id"),
    5: .standard(proto: "context_user"),
    2: .standard(proto: "new_device_name"),
    3: .standard(proto: "new_mfa_response"),
    4: .standard(proto: "device_usage"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.tokenID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.newDeviceName) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._newMfaResponse) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.deviceUsage) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._contextUser) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.tokenID.isEmpty {
      try visitor.visitSingularStringField(value: self.tokenID, fieldNumber: 1)
    }
    if !self.newDeviceName.isEmpty {
      try visitor.visitSingularStringField(value: self.newDeviceName, fieldNumber: 2)
    }
    try { if let v = self._newMfaResponse {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.deviceUsage != .unspecified {
      try visitor.visitSingularEnumField(value: self.deviceUsage, fieldNumber: 4)
    }
    try { if let v = self._contextUser {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_AddMFADeviceSyncRequest, rhs: Proto_AddMFADeviceSyncRequest) -> Bool {
    if lhs.tokenID != rhs.tokenID {return false}
    if lhs._contextUser != rhs._contextUser {return false}
    if lhs.newDeviceName != rhs.newDeviceName {return false}
    if lhs._newMfaResponse != rhs._newMfaResponse {return false}
    if lhs.deviceUsage != rhs.deviceUsage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Proto_AddMFADeviceSyncResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AddMFADeviceSyncResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "device"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.device) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.device.isEmpty {
      try visitor.visitSingularBytesField(value: self.device, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Proto_AddMFADeviceSyncResponse, rhs: Proto_AddMFADeviceSyncResponse) -> Bool {
    if lhs.device != rhs.device {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
