// SPDX-License-Identifier: AGPL-3.0-or-later
//
//  FixtureTests.swift
//  VVTermTests
//
//  Byte-compares Swift output against Go-generated fixtures to catch
//  transcription errors in the CBOR / attestation / clientDataJSON building.
//
//  Ported verbatim from spikes/sep-webauthn/Tests/SEPWebAuthnTests/FixtureTests.swift.
//  Two adaptations for the VVTermTests target:
//    1. `@testable import VVTerm` (was `@testable import SEPWebAuthn`) — the
//       SEPWebAuthn sources now live in the VVTerm app module.
//    2. Fixture path resolution walks up to the repo root then into
//       `spikes/sep-webauthn/fixtures/expected/` (the fixtures are generated
//       at CI time by `spikes/sep-webauthn/fixtures/regenerate.sh`, driven by
//       `.github/workflows/sep-webauthn-fixtures.yml`).
//
//  The Go fixtures are generated by `spikes/sep-webauthn/fixtures/generate/main.go`
//  (run on a `macos-14` runner or any Mac with Go installed) and written under
//  `spikes/sep-webauthn/fixtures/expected/*.bin`. Regenerate with
//  `spikes/sep-webauthn/fixtures/regenerate.sh`.
//
//  What's compared:
//    - collectedClientData JSON bytes (3-field form, base64url challenge)
//    - authenticatorData bytes (rpIdHash || flags || signCount || [attData])
//    - COSE EC2 public key CBOR bytes
//    - full attestation object CBOR bytes (with a known signature)
//
//  What's NOT compared (because it's non-deterministic):
//    - The signature itself (depends on the private key, which is random).
//      The fixture generator uses a FIXED private key so the signature IS
//      deterministic; the Swift side can't reproduce it without the same
//      key. Instead, we verify the signature verifies against the public
//      key, and byte-compare everything else.

import XCTest
@testable import VVTerm
import CryptoKit

final class FixtureTests: XCTestCase {

    // Test vector — MUST match fixtures/generate/main.go exactly.
    // (Changing these requires regenerating the fixtures.)
    static let origin       = "https://goteleport.com"
    static let rpID         = "goteleport.com"
    static let challenge    = Data([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
    static let credentialID = "11111111-2222-3333-4444-555555555555"  // UUID string, like api.go uses
    // The fixed P-256 public key is loaded from fixtures/expected/pub_key_raw.bin
    // at test time (65 bytes, 0x04 || X || Y) — matches the Go fixture's key.

    // MARK: - helpers

    private func fixtureBaseURL() -> URL {
        // This test file lives at VVTermTests/Features/Teleport/SEPWebAuthn/.
        // Fixtures live at spikes/sep-webauthn/fixtures/expected/ (relative to
        // the repo root). Walk up from this file to the repo root, then down
        // into the spike's fixtures/expected/ directory.
        //
        // The fixtures are generated at CI time by
        // `spikes/sep-webauthn/fixtures/regenerate.sh` (driven by
        // `.github/workflows/sep-webauthn-fixtures.yml`). They are NOT
        // committed — the generator writes them fresh on each CI run so the
        // byte-comparison always reflects the current Go reference output.
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // remove FixtureTests.swift
            .deletingLastPathComponent()  // remove SEPWebAuthn/
            .deletingLastPathComponent()  // remove Teleport/
            .deletingLastPathComponent()  // remove Features/
            .deletingLastPathComponent()  // remove VVTermTests/
        return repoRoot
            .appendingPathComponent("spikes/sep-webauthn/fixtures/expected")
    }

    private func loadFixtureIfPresent(_ name: String) throws -> Data? {
        let url = fixtureBaseURL().appendingPathComponent(name)
        guard FileManager.default.fileExists(atPath: url.path) else {
            return nil
        }
        return try Data(contentsOf: url)
    }

    // MARK: - tests

    func testCollectedClientDataJSON_matchesGoFixture() throws {
        // Go fixture: fixtures/expected/client_data_create.json
        // (and client_data_get.json for the assertion ceremony)
        let ccd = CollectedClientData(
            type: CeremonyType.create.rawValue,
            challenge: Self.challenge.base64URLEncodedString(),
            origin: Self.origin
        )
        let swiftJSON = ccd.toJSONBytes()

        let expected = try loadFixtureIfPresent("client_data_create.json")
        guard let expected else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(
            swiftJSON, expected,
            "clientDataJSON mismatch (create ceremony).\n" +
            "Swift: \(String(data: swiftJSON, encoding: .utf8) ?? "<bin>")\n" +
            "Go:    \(String(data: expected, encoding: .utf8) ?? "<bin>")"
        )

        // Also check the get ceremony.
        let ccdGet = CollectedClientData(
            type: CeremonyType.get.rawValue,
            challenge: Self.challenge.base64URLEncodedString(),
            origin: Self.origin
        )
        let swiftJSONGet = ccdGet.toJSONBytes()
        let expectedGet = try loadFixtureIfPresent("client_data_get.json")
        guard let expectedGet else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(
            swiftJSONGet, expectedGet,
            "clientDataJSON mismatch (get ceremony).\n" +
            "Swift: \(String(data: swiftJSONGet, encoding: .utf8) ?? "<bin>")\n" +
            "Go:    \(String(data: expectedGet, encoding: .utf8) ?? "<bin>")"
        )
    }

    func testAuthenticatorData_matchesGoFixture() throws {
        // Load the fixed public key from the fixture.
        let pubKeyRawData = try loadFixtureIfPresent("pub_key_raw.bin")
        guard let pubKeyRaw = pubKeyRawData else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(pubKeyRaw.count, 65, "pub key should be 65 bytes")
        XCTAssertEqual(pubKeyRaw[0], 0x04, "pub key should start with 0x04")

        let pubKeyCBOR = try coseEC2PublicKeyCBOR(publicKeyRaw: pubKeyRaw)
        let cred = CredentialData(
            id: Data(Self.credentialID.utf8),
            pubKeyCBOR: pubKeyCBOR
        )
        let attData = try makeAttestationData(
            ceremony: .create,
            origin: Self.origin,
            rpID: Self.rpID,
            challenge: Self.challenge,
            cred: cred
        )

        // Compare the COSE public key CBOR.
        let expectedPubKeyCBOR = try loadFixtureIfPresent("cose_pubkey.cbor")
        guard let expectedPubKeyCBOR else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(
            pubKeyCBOR, expectedPubKeyCBOR,
            "COSE EC2 public key CBOR mismatch.\n" +
            "Swift: \(pubKeyCBOR.map { String(format: "%02x", $0) }.joined())\n" +
            "Go:    \(expectedPubKeyCBOR.map { String(format: "%02x", $0) }.joined())"
        )

        // Compare the authenticatorData bytes.
        let expectedAuthData = try loadFixtureIfPresent("auth_data_create.bin")
        guard let expectedAuthData else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(
            attData.rawAuthData, expectedAuthData,
            "authenticatorData mismatch (create).\n" +
            "Swift: \(attData.rawAuthData.map { String(format: "%02x", $0) }.joined())\n" +
            "Go:    \(expectedAuthData.map { String(format: "%02x", $0) }.joined())"
        )

        // get ceremony authData (no attested credential data).
        let attDataGet = try makeAttestationData(
            ceremony: .get,
            origin: Self.origin,
            rpID: Self.rpID,
            challenge: Self.challenge,
            cred: nil
        )
        let expectedAuthDataGet = try loadFixtureIfPresent("auth_data_get.bin")
        guard let expectedAuthDataGet else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(
            attDataGet.rawAuthData, expectedAuthDataGet,
            "authenticatorData mismatch (get).\n" +
            "Swift: \(attDataGet.rawAuthData.map { String(format: "%02x", $0) }.joined())\n" +
            "Go:    \(expectedAuthDataGet.map { String(format: "%02x", $0) }.joined())"
        )
    }

    func testAttestationObject_matchesGoFixture() throws {
        // Compare the full attestation object CBOR against the Go-generated
        // fixture. The Go generator produces the attestation object with a
        // FIXED private key so the signature is deterministic, and writes
        // both the signature and the full attObj to fixtures/expected/.
        //
        // We reproduce the same authData (via the fixed test inputs) and
        // pass the Go fixture's signature into buildAttestationObjectCBOR,
        // then byte-compare the result against the Go attObj fixture.
        let pubKeyRawData = try loadFixtureIfPresent("pub_key_raw.bin")
        guard let pubKeyRaw = pubKeyRawData else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        let pubKeyCBOR = try coseEC2PublicKeyCBOR(publicKeyRaw: pubKeyRaw)
        let cred = CredentialData(
            id: Data(Self.credentialID.utf8),
            pubKeyCBOR: pubKeyCBOR
        )
        let attData = try makeAttestationData(
            ceremony: .create, origin: Self.origin, rpID: Self.rpID,
            challenge: Self.challenge, cred: cred
        )

        // Load the Go-generated signature (deterministic — fixed priv key).
        let goSignatureData = try loadFixtureIfPresent("signature_create.der")
        guard let goSignature = goSignatureData else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }

        // Build the Swift attObj with the Go fixture's signature.
        let swiftAttObj = WebAuthn.buildAttestationObjectCBOR(
            authData: attData.rawAuthData,
            signature: goSignature
        )

        // Compare against the Go-generated attObj fixture.
        let expectedAttObj = try loadFixtureIfPresent("attestation_object_create.cbor")
        guard let expectedAttObj else {
            throw XCTSkip("Fixtures not present — generated by sep-webauthn-fixtures.yml workflow")
        }
        XCTAssertEqual(
            swiftAttObj, expectedAttObj,
            "attestation object CBOR mismatch.\n" +
            "Swift: \(swiftAttObj.map { String(format: "%02x", $0) }.joined())\n" +
            "Go:    \(expectedAttObj.map { String(format: "%02x", $0) }.joined())"
        )
    }

    // MARK: - software signer round-trip (no Go fixture needed)

    func testSoftwareSigner_signatureVerifiesAgainstPublicKey() throws {
        // Generate a software key, sign a digest, verify the signature
        // against the extracted public key. This catches gross bugs in the
        // signer / digest-passing path that would cause server rejection.
        let signer = SoftwareSigner()
        let (credID, pubKeyRaw) = try signer.createKey()
        XCTAssertEqual(pubKeyRaw.count, 65)
        XCTAssertEqual(pubKeyRaw[0], 0x04)

        // Build a create-ceremony attestation, sign the message.
        let pubKeyCBOR = try coseEC2PublicKeyCBOR(publicKeyRaw: pubKeyRaw)
        let attData = try makeAttestationData(
            ceremony: .create, origin: Self.origin, rpID: Self.rpID,
            challenge: Self.challenge,
            cred: CredentialData(id: credID, pubKeyCBOR: pubKeyCBOR)
        )
        let sig = try signer.sign(message: attData.message, credentialID: credID)
        XCTAssertGreaterThanOrEqual(sig.count, 8, "DER ECDSA sig should be ≥8 bytes")
        XCTAssertLessThanOrEqual(sig.count, 72, "DER ECDSA sig should be ≤72 bytes")

        // Verify with CryptoKit: the server computes sha256(message) and
        // verifies. CryptoKit's isValidSignature(sig, for: SHA256.hash(data:))
        // does the same single hash.
        let p256Key = try P256.Signing.PublicKey(x963Representation: pubKeyRaw)
        let derSig = try P256.Signing.ECDSASignature(derRepresentation: sig)
        let messageDigest = SHA256.hash(data: attData.message)
        XCTAssertTrue(
            p256Key.isValidSignature(derSig, for: messageDigest),
            "SoftwareSigner signature failed to verify against its public key"
        )
    }

    func testCredentialID_isUUIDString_forProductionParity() throws {
        // In api_darwin.go:204 the credential ID is `uuid.NewString()`.
        // The spike uses a base64url-encoded random 32-byte value — this
        // is fine for the wire format (any opaque string works), but let's
        // confirm the CLI uses something string-shaped so the `id`/`rawId`
        // base64url encoding round-trips correctly.
        let signer = SoftwareSigner()
        let (credID, _) = try signer.createKey()
        let credIDString = credID.base64URLEncodedString()
        XCTAssertFalse(credIDString.isEmpty, "credential ID string must not be empty")
        // Round-trip: decode the base64url string back to bytes, should
        // equal the original credential ID bytes.
        let decoded = Data(base64URLEncoded: credIDString)
        XCTAssertEqual(decoded, credID, "credential ID base64url decode failed")
    }
}
